=== Niklasmh/Webtech-project/data/artists.dtd
<!--

FILE NAME: Project/data/artists.dtd

WRITTEN BY: Øyvind Auestad Bjørhus

WHEN: 10. November 2015

PURPOSE: Make a structure for artists.xml

-->

<!ELEMENT music (genres, groups)>

<!ELEMENT genres (genre)>

<!ELEMENT genre (sub_genre)*>
<!ATTLIST genre name CDATA #REQUIRED>

<!ELEMENT sub_genre (genre_group)+>
<!ATTLIST sub_genre name CDATA #REQUIRED>

<!ELEMENT genre_group EMPTY>
<!ATTLIST  genre_group id IDREF #REQUIRED>

<!ELEMENT groups (group)>

<!ELEMENT group (name, group_members, start_date, picture, songs, tags)*>
<!ATTLIST group name CDATA #REQUIRED>
<!ATTLIST group id IDREF #REQUIRED>

<!ELEMENT group_members (group_member)+>
<!ELEMENT start_date (#PCDATA)>
<!ELEMENT songs (song)*>
<!ELEMENT tags (tag)*>

<!ELEMENT group_member EMPTY>
<!ATTLIST group_member name CDATA #REQUIRED>

<!ELEMENT picture EMPTY>
<!ATTLIST picture src CDATA "false">
<!ATTLIST picture alt CDATA #REQUIRED>

<!ELEMENT song EMPTY>
<!ATTLIST song title CDATA #REQUIRED>
<!ATTLIST song length CDATA "false">
<!ATTLIST song src CDATA "false">

<!ELEMENT tag EMPTY>
<!ATTLIST tag name CDATA #REQUIRED>

=== Niklasmh/Webtech-project/data/artists.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE music SYSTEM "artists.dtd">

<!--

FILE NAME: Project/data/artists.xml

WRITTEN BY: Øyvind Auestad Bjørhus

WHEN: 25. Oktober 2015

PURPOSE: An API to fetch artist data.

-->

<music>
    <genres>
        <genre name="rock">
            <sub_genre name="hard_rock">
                <genre_group group="g1"/>
                <genre_group group="g2"/>
                <genre_group group="g3"/>
            </sub_genre>
            <sub_genre name="blues_rock">
                <genre_group group="g2"/>
            </sub_genre>
        </genre> 
        <genre name="metal">
            <sub_genre name="metal_core">
                <genre_group group="g14"/>
            </sub_genre>
            <sub_genre name="heavy_metal">
                <genre_group group="g14"/>
                <genre_group group="g16"/>
            </sub_genre>
        </genre>
        <genre name="pop">
            <sub_genre name="lovepop">
                <genre_group group="g6"/>
            </sub_genre>
            <sub_genre name="indiepop">
                <genre_group group="g5"/>
            </sub_genre>
        </genre>
        <genre name="jazz">
            <sub_genre name="nu_jazz">
                <genre_group group="g7"/>
            </sub_genre>
            <sub_genre name="bebop">
                <genre_group group="g8"/>
            </sub_genre>
        </genre>
         <genre name="klassisk">
            <sub_genre name="barokken">
                <genre_group group="g9"/>
            </sub_genre>
            <sub_genre name="romantikken">
                <genre_group group="g10"/>
            </sub_genre>
        </genre>
        <genre name="hiphop">
            <sub_genre name="trap">
                <genre_group group="g12"/>
            </sub_genre>
            <sub_genre name="alternative_rap">
                <genre_group group="g11"/>
            </sub_genre>
            <sub_genre name="pop_rap">
                <genre_group group="g4"/>
            </sub_genre>
        </genre>
        <genre name="elektronisk">
            <sub_genre name="trance">
                <genre_group group="g13"/>
            </sub_genre>
            <sub_genre name="ambient">
                <genre_group group="g15"/>
            </sub_genre>
        </genre>
        <genre name="støy">
            <sub_genre name="hvit_støy">
                <genre_group group="g17"/>
            </sub_genre>
            <sub_genre name="brun_støy">
                <genre_group group="g18"/>
            </sub_genre>
            <sub_genre name="rosa_støy">
                <genre_group group="g3"/>
                <genre_group group="g19"/>
            </sub_genre>
        </genre>
    </genres>
    <groups>
        <group name="kiss" id="g1">
            <start_date>2014-01-05T09:50:21Z</start_date>
			<picture src="./images/artistimages/kiss.jpg" alt="Kiss på scenen"/>
            <group_members>
                <group_member name="krisian arnesen"/>
                <group_member name="tor haugen"/>
            </group_members>
            <songs>
                <song title="yoloswag" length="3:56" src="./media/audio/Death Grips - Get Got.mp3"/>
                <song title="yoyogo" length="2:07"/>
                <song title="julenissen spiser grøt" length="5:20"/>
            </songs>
			<tags>
				<tag name="heftig"/>
				<tag name="bra"/>
				<tag name="rock"/>
				<tag name="amerikansk"/>
                
			</tags>
			<description>I motsetning til hva mange tror, er ikke Lorem Ipsum bare tilfeldig tekst. Dets røtter springer helt tilbake til et stykke klassisk latinsk litteratur fra 45 år f.kr., hvilket gjør det over 2000 år gammelt. Richard McClintock - professor i latin ved Hampden-Sydney College i Virginia, USA - slo opp flere av de mer obskure latinske ordene, consectetur, fra en del av Lorem Ipsum, og fant dets utvilsomme opprinnelse gjennom å studere bruken av disse ordene i klassisk litteratur. Lorem Ipsum kommer fra seksjon 1.10.32 og 1.10.33 i "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) av Cicero, skrevet i år 45 f.kr. Boken er en avhandling om teorier rundt etikk, og var veldig populær under renessansen. Den første linjen av Lorem Ipsum, "Lorem Ipsum dolor sit amet...", er hentet fra en linje i seksjon 1.10.32. Standardbiten av Lorem Ipsum brukt siden 1500-tallet er gjengitt nedenfor for spesielt interesserte. Seksjon 1.10.32 og 1.10.33 fra "de Finibus Bonorum et Malorum" av Cicero er også eksakt gjengitt, akkompagnert av engelske versjoner fra 1914-oversettelsen av H. Rackham.</description>
        </group>
        <group name="aerosmith" id="g2">
            <start_date>2015-01-10T09:50:21Z</start_date>
			<picture src="./images/artistimages/aerosmith.jpg" alt="Aerosmith på scenen igjen"/>
            <group_members>
                <group_member name="arne jarl"/>
                <group_member name="brage husodd"/>
            </group_members>
            <songs>
                <song title="vi lever for alltid" length="9:56" src="./media/audio/Best Coast - The Only Place.mp3" />
                <song title="bestevenner igjen" length="4:07"/>
                <song title="janteloven er life" length="6:20"/>
            </songs>
			<tags>
				<tag name="metal"/>
				<tag name="rock"/>
				<tag name="bra"/>
                <tag name="amerikansk"/>
			</tags>
			<description>Ut commodo risus ac fermentum vulputate. In hendrerit mattis lorem. Suspendisse risus ipsum, rutrum condimentum neque et,        lacinia dapibus tortor. Vivamus laoreet ipsum vitae urna ullamcorper, eleifend ornare lorem placerat. Donec congue non felis imperdiet semper. Proin nibh elit, elementum sit amet diam id, vehicula maximus orci. Vivamus libero erat, tristique sed mollis ac, maximus at turpis. Sed sed convallis felis, a accumsan enim. Nullam sit amet pharetra sapien, vehicula porttitor arcu.</description>
        </group>
        <group name="mystery" id="g3">
            <start_date>2014-02-05T09:50:21Z</start_date>
			<picture src="./images/artistimages/mystery.jpg" alt="sigve lengst til høyre"/>
            <group_members>
                <group_member name="sigve skaugvoll og andre ukjente medlemmer"/>
            </group_members>
            <songs>
                <song title="rock e sunt" length="3:02" src="./media/audio/Com Truise - Cyanide Sisters.mp3" />
            </songs>
			<tags>
				<tag name="hard"/>
				<tag name="ass"/>
				<tag name="niggah"/>
                <tag name="das_racis"/>
                <tag name="norsk"/>
			</tags>
			<description>Ut commodo risus ac fermentum vulputate. In hendrerit mattis lorem. Suspendisse risus ipsum, rutrum condimentum neque et,        lacinia dapibus tortor. Vivamus laoreet ipsum vitae urna ullamcorper, eleifend ornare lorem placerat. Donec congue non felis imperdiet semper. Proin nibh elit, elementum sit amet diam id, vehicula maximus orci. Vivamus libero erat, tristique sed mollis ac, maximus at turpis. Sed sed convallis felis, a accumsan enim. Nullam sit amet pharetra sapien, vehicula porttitor arcu.</description>
        </group>
        <group name="kanye west" id="g4">
            <start_date>2015-02-05T09:50:21Z</start_date>
			<picture src="./images/artistimages/kanyewest.jpg" alt="Kanye West"/>
            <group_members>
                <group_member name="kanye west"/>
            </group_members>
            <songs>
                <song title="beat it" length="7:22" src="./media/audio/Death Grips - Bass Rattle Stars Out the Sky.mp3"/>
            </songs>
			<tags>
				<tag name="hard"/>
				<tag name="ass"/>
				<tag name="niggah$"/>
                <tag name="das_racis"/>
                <tag name="pop"/>
			</tags>
			<description>Ut commodo risus ac fermentum vulputate. In hendrerit mattis lorem. Suspendisse risus ipsum, rutrum condimentum neque et,        lacinia dapibus tortor. Vivamus laoreet ipsum vitae urna ullamcorper, eleifend ornare lorem placerat. Donec congue non felis imperdiet semper. Proin nibh elit, elementum sit amet diam id, vehicula maximus orci. Vivamus libero erat, tristique sed mollis ac, maximus at turpis. Sed sed convallis felis, a accumsan enim. Nullam sit amet pharetra sapien, vehicula porttitor arcu.</description>
        </group>
        <group name="wingsuits" id="g5">
            <start_date>2014-03-05T09:50:21Z</start_date>
			<picture src="./images/artistimages/wingsuits.jpg" alt="wingsuits posing"/>
            <group_members>
                <group_member name="Jørgen Thorsnes"/>
                <group_member name="Fredrik Feyling"/>
                <group_member name="Haavard Nøst"/>
                <group_member name="Isak Adserø"/>
                <group_member name="Herman Nøst"/>
            </group_members>
            <songs>
                <song title="suit me" length="3:02" src="./media/audio/01 Suit Me.mp3"/>
            </songs>
			<tags>
				<tag name="kjærleik"/>
				<tag name="indie"/>
                <tag name="norsk"/>
			</tags>
			<description>Ut commodo risus ac fermentum vulputate. In hendrerit mattis lorem. Suspendisse risus ipsum, rutrum condimentum neque et,        lacinia dapibus tortor. Vivamus laoreet ipsum vitae urna ullamcorper, eleifend ornare lorem placerat. Donec congue non felis imperdiet semper. Proin nibh elit, elementum sit amet diam id, vehicula maximus orci. Vivamus libero erat, tristique sed mollis ac, maximus at turpis. Sed sed convallis felis, a accumsan enim. Nullam sit amet pharetra sapien, vehicula porttitor arcu.</description>
        </group>
        <group name="beyoncé" id="g6">
            <start_date>2015-03-05T09:50:21Z</start_date>
			<picture src="./images/artistimages/beyonce.jpg" alt="Beyoncé"/>
            <group_members>
                <group_member name="beyoncé"/>
            </group_members>
            <songs>
                <song title="all the single laeydies" length="5:43" src="./media/audio/Death Grips - Blackjack.mp3"/>
